# install.packages("BiocManager")
# BiocManager::install(version = "3.20")
BiocManager::install("tidyverse")
BiocManager::install("arrayQualityMetrics")
BiocManager::install("lubridate")
BiocManager::install("BiocManager")
BiocManager::install("SCAN.UPC")
BiocManager::install("GEOquery")
BiocManager::install("clariomshumancdf")
BiocManager::install("arrayQualityMetrics")
BiocManager::install("pd.clariom.s.human")
BiocManager::install("arrayQualityMetrics")
BiocManager::install("affy")
BiocManager::install("clariomshumanhsentrezgprobe")
BiocManager::install("doParallel")